apiVersion: v2
name: llm-orch
description: Helm chart for deploying llm-orch
icon: https://raw.githubusercontent.com/zen-xu/llm-orch/main/docs/assets/logo.png
type: application
version: 0.1.0
appVersion: "0.1.0"
