defaults:
  temperature: 0.2
  max_tokens: 2048
  task_header: "x-orch-task-kind"
  sticky_header: "x-orch-sticky-key"
routes:
  PLAN:
    strategy: priority
    targets:
      - provider: frontier_primary
        circuit_breaker:
          failure_threshold: 3
          recovery_time_s: 60
      - provider: frontier_backup
  CRITIQUE:
    strategy: weighted
    targets:
      - provider: frontier_primary
        weight: 3
      - provider: frontier_backup
        weight: 1
  CODE:
    strategy: sticky
    sticky_ttl: 30
    targets:
      - provider: hosted_fast
      - provider: local_7b
  SUMMARY:
    primary: hosted_fast
    fallback:
      - local_7b
  BULK:
    primary: local_7b
    fallback:
      - hosted_fast
  DEFAULT:
    primary: hosted_fast
    fallback:
      - frontier_primary
      - local_7b
