{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- $fullname := default (printf "%s-%s" .Release.Name $name) .Values.fullnameOverride -}}
{{- $labels := dict "app.kubernetes.io/name" $name "app.kubernetes.io/instance" .Release.Name "app.kubernetes.io/managed-by" "Helm" -}}
{{- $serviceAccount := default (dict) .Values.serviceAccount -}}
{{- $serviceAccountCreate := default true $serviceAccount.create -}}
{{- if $serviceAccountCreate }}
{{- $serviceAccountName := coalesce $serviceAccount.name (printf "%s-sa" $fullname) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName | trunc 63 | trimSuffix "-" }}
  labels:
{{- range $key, $value := $labels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- with $serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
automountServiceAccountToken: {{ default false $serviceAccount.automount }}
{{- end }}
