name: pr-gate
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  gate:
    runs-on: ubuntu-latest
    permissions: {contents: read, pull-requests: write}
    steps:
      - uses: actions/checkout@v4
      - name: Check CODEOWNERS approval
        uses: actions/github-script@v7
        with:
          script: |
            const query = `
              query($owner: String!, $repo: String!, $number: Int!) {
                repository(owner: $owner, name: $repo) {
                  pullRequest(number: $number) {
                    reviewDecision
                  }
                }
              }
            `;
            const result = await github.graphql(query, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              number: context.issue.number,
              headers: {
                accept: 'application/vnd.github.merge-info-preview+json',
                'GraphQL-Features': 'pull-request-review-decision',
              },
            });
            const pullRequest = result.repository?.pullRequest;
            if (!pullRequest) {
              core.warning('Pull request metadata unavailable; skipping review decision gate.');
              return;
            }
            const rawDecision = pullRequest.reviewDecision;
            if (typeof rawDecision !== 'string') {
              core.warning('No review decision returned; defaulting to REVIEW_REQUIRED.');
            }
            const decision = (typeof rawDecision === 'string' ? rawDecision : undefined) ?? 'REVIEW_REQUIRED';
            if (decision === 'CHANGES_REQUESTED') {
              core.setFailed('Pull request has changes requested');
              return;
            }
            if (decision !== 'APPROVED') {
              core.notice(`Pull request review decision is ${decision}`);
            }
      - name: Block auto-merge
        run: |
          echo "Auto merge is disabled by policy"
          exit 0
