name: pr-gate
on: [pull_request]
jobs:
  gate:
    runs-on: ubuntu-latest
    permissions: {contents: read, pull-requests: write}
    steps:
      - uses: actions/checkout@v4
      - name: Check CODEOWNERS approval
        uses: actions/github-script@v7
        with:
          script: |
            const query = `
              query($owner: String!, $repo: String!, $number: Int!) {
                repository(owner: $owner, name: $repo) {
                  pullRequest(number: $number) {
                    reviewDecision
                  }
                }
              }
            `;
            const result = await github.graphql(query, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              number: context.issue.number,
              headers: {
                accept: 'application/vnd.github.merge-info-preview+json',
                'GraphQL-Features': 'pull-request-review-decision',
              },
            });
            const decision = result.repository.pullRequest?.reviewDecision;
            if (decision !== 'APPROVED') {
              core.setFailed(`Pull request review decision is ${decision ?? 'UNKNOWN'}`);
            }
      - name: Block auto-merge
        run: |
          echo "Auto merge is disabled by policy"
          exit 0
